# Generated by Django 3.2 on 2023-11-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231126_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='image_url',
            new_name='imagen',
        ),
    ]
